name: Deploy Hugo Catalog

on:
  push:
    branches:
      - main # Set a branch to deploy
  schedule:
   - cron: "0 0 * * *"
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:

      - name: Checking our files from restore branch
        if: github.event.schedule == '0 0 * * *'
        run: echo "Deploying Hugo Catalog Playground from restore branch"

      - uses: actions/checkout@v4
        if: github.event.schedule == '0 0 * * *'
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          ref: restore

      - name: Checking our files from main branch
        if: github.event.schedule != '0 0 * * *'
        run: echo "Deploying Hugo Catalog Playground from main branch"

      - uses: actions/checkout@v4
        if: github.event.schedule != '0 0 * * *'
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Hugo deploy
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: hugo --minify --baseURL ${{secrets.BASE_URL}}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
